# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-20 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctormember',
            old_name='user',
            new_name='primary_user',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='user',
            new_name='primary_user',
        ),
        migrations.AddField(
            model_name='abstractmember',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abstractmember',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
