# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-20 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20161220_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractmember',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='abstractmember',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
