# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-23 09:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('date', models.DateField()),
                ('state', models.CharField(choices=[('N', 'Requested'), ('A', 'Accepted'), ('R', 'Rejected'), ('C', 'Canceled'), ('P', 'Postponed')], default='N', max_length=1)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.DoctorMember')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
        ),
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.SmallIntegerField()),
                ('start_time', models.TimeField(default=datetime.time(9, 0))),
                ('end_time', models.TimeField(default=datetime.time(17, 0))),
            ],
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_interval', models.PositiveIntegerField(default=30)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='member.DoctorMember')),
            ],
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='doctor_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.DoctorSchedule'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('schedule.appointmentrequest',),
        ),
    ]
