# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-19 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyschedule',
            name='doctor_schedule',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schedule.DoctorSchedule'),
            preserve_default=False,
        ),
    ]
