# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-27 14:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 27, 14, 21, 52, 94670)),
        ),
    ]
