# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-04 09:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20170127_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 4, 9, 59, 38, 632371)),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='state',
            field=models.CharField(choices=[('N', 'Requested'), ('A', 'Accepted'), ('R', 'Rejected'), ('C', 'Canceled'), ('P', 'Postponed')], default='N', max_length=1),
        ),
    ]
